# Generated by Django 4.2.11 on 2026-03-15 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0002_navmenu_header_buttons_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Component identifier (e.g., 'heading')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('layout', 'Layout Components'), ('content', 'Content Components'), ('media', 'Media Components'), ('form', 'Form Components')], max_length=20)),
                ('icon', models.CharField(help_text="Material Design icon name (e.g., 'mdi:format-title')", max_length=100)),
                ('label', models.CharField(help_text='Human-readable label', max_length=100)),
                ('schema', models.JSONField(help_text='JSON Schema for component properties')),
                ('default_props', models.JSONField(help_text='Default property values')),
                ('is_enabled', models.BooleanField(default=True)),
                ('requires_asset', models.BooleanField(default=False, help_text='Does component need an image/file?')),
                ('is_editable', models.BooleanField(default=True, help_text='Can component content be edited inline?')),
                ('render_component', models.CharField(help_text="React component path (e.g., 'builder.components.Heading')", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in palette')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Registry',
                'verbose_name_plural': 'Component Registry',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuilderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('builder_data', models.JSONField(help_text='Component structure for template')),
                ('is_public', models.BooleanField(default=True, help_text='Available to all users')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Builder Template',
                'verbose_name_plural': 'Builder Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuilderPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_version', models.PositiveIntegerField(default=1)),
                ('last_auto_save', models.DateTimeField(auto_now_add=True)),
                ('grid_enabled', models.BooleanField(default=True)),
                ('snap_to_grid', models.BooleanField(default=True)),
                ('grid_size', models.PositiveIntegerField(default=12, help_text='Grid size in pixels')),
                ('current_viewport', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('show_rulers', models.BooleanField(default=False)),
                ('show_outlines', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_settings', to='marketing.page')),
            ],
            options={
                'verbose_name': 'Builder Page Settings',
                'verbose_name_plural': 'Builder Page Settings',
            },
        ),
        migrations.CreateModel(
            name='BuilderAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('icon', 'Icon')], max_length=20)),
                ('file', models.URLField(help_text='Cloudinary URL', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('upload_source', models.CharField(choices=[('builder', 'Page Builder Upload'), ('direct', 'Direct URL Entry'), ('cloudinary', 'Cloudinary Upload'), ('unsplash', 'Unsplash Search')], default='builder', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Alt text, dimensions, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_builder_assets', to=settings.AUTH_USER_MODEL)),
                ('used_in_pages', models.ManyToManyField(blank=True, help_text='Pages using this asset', related_name='builder_assets', to='marketing.page')),
            ],
            options={
                'verbose_name': 'Builder Asset',
                'verbose_name_plural': 'Builder Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
