# Generated by Django 4.2.11 on 2026-03-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_componentregistry_buildertemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builderasset',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='builderasset',
            name='used_in_pages',
        ),
        migrations.RemoveField(
            model_name='builderpagesettings',
            name='page',
        ),
        migrations.RemoveField(
            model_name='buildertemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ComponentRegistry',
        ),
        migrations.DeleteModel(
            name='BuilderAsset',
        ),
        migrations.DeleteModel(
            name='BuilderPageSettings',
        ),
        migrations.DeleteModel(
            name='BuilderTemplate',
        ),
    ]
